### PR TITLE
Increase test coverage and refactor code

### LINKED ISSUE #7: Test threshold
# General Support Request

The current test threshold is sub-par

```
=============================== Coverage summary ===============================
Statements   : 79.41% ( 27/34 )
Branches     : 100% ( 1/1 )
Functions    : 80% ( 8/10 )
Lines        : 79.41% ( 27/34 )
================================================================================
```

## Support request

Update tests to meet 80% threshold

### PR DESCRIPTION
**Pull request by geoffrich**
# Alaska Airlines Pull Request

Fixes #7

## Summary:

This PR increases the test coverage above 90% and refactors the tests for readability.

```
  auro-popover
    ✔ is accessible
    ✔ custom element is defined
    when "sticky" attribute set to true
      ✔ shows popover when you click trigger element
      ✔ closes when user clicks anything else that isn't the trigger or popover
      ✔ closes when there is an action inside the popover to close it
      ✔ hides on tab key
      ✔ hides on hidePopover event
      ✔ toggles shown state

Finished in 0.174 secs / 0.123 secs @ 16:14:25 GMT-0800 (Pacific Standard Time)

SUMMARY:
✔ 8 tests completed

=============================== Coverage summary ===============================
Statements   : 100% ( 42/42 )
Branches     : 91.67% ( 11/12 )
Functions    : 100% ( 15/15 )
Lines        : 100% ( 42/42 )
===============================================================================
```

It also performs the following refactorings and fixes (all in separate commits):
- Remove need for process.env patching by using the [browser-native version](https://github.com/popperjs/popper-core#distribution-targets) of @popperjs/core
- Make code indentation more consistent
- Move common hide/show functionality into methods
- Clean up the document click event listener in disconnected callback

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by geoffrich** [comment]
It would also be good to get @BrentLabasan's eyes on this to make sure my refactoring didn't break anything he just added.

**Review by gusnaughton — APPROVED** [review]
Looks great to me - thanks for finding the esm build fix!

**Review by BrentLabasan — APPROVED** [review]
Looks good to me.

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
